# Generated by Django 5.1.6 on 2025-04-04 22:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='name',
            new_name='business_name',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='sent_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='business',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='business',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='business',
            name='business_email',
            field=models.EmailField(default='default@email.com', max_length=254),
        ),
        migrations.AddField(
            model_name='business',
            name='business_phone',
            field=models.CharField(default='default@email.com', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 4, 22, 22, 59, 575635, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='payments.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='payments.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='payments.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], default='credit', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='Diagnostic_56', max_length=128),
            preserve_default=False,
        ),
    ]
