# Generated by Django 5.1.6 on 2025-04-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_name_business_business_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('business_owner', 'Business Owner')], default='customer', max_length=20),
        ),
    ]
